"""
Django settings for fermesenegalaise project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

import environ

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

env = environ.Env()
# .env lives at the repo root and is git-ignored, see .env.example for the
# full list of variables a deployment needs to set.
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "core",
    "home",
    "pages",
    "activities",
    "products",
    "news",
    "gallery",
    "locations",
    "contact",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.routable_page",
    "wagtail.contrib.sitemaps",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "fermesenegalaise.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
                "core.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "fermesenegalaise.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
# Site launches in French only. WAGTAIL_I18N_ENABLED is deliberately left off
# for now (see README "Passage au bilingue") so the content tree stays simple;
# turning it on later lets English be added without rebuilding page models.

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Dakar"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "La Ferme Sénégalaise"

# Content editors only need the standard rich text controls; keeping this
# curated avoids the "amateur" look that comes from letting editors set
# arbitrary fonts/colors inline in a corporate site.
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    "default": {
        "WIDGET": "wagtail.admin.rich_text.DraftailRichTextArea",
        "OPTIONS": {
            "features": [
                "bold", "italic", "link", "ol", "ul", "hr",
                "h2", "h3", "h4", "document-link", "image", "embed",
            ]
        },
    }
}

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = env("BASE_URL", default="http://localhost:8000")

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Maximum upload size for documents in bytes.
WAGTAILDOCS_MAX_UPLOAD_SIZE = 20 * 1024 * 1024  # 20MB

# Image renditions above this size are rejected: protects the server from
# an editor uploading an unoptimised 40 MB camera photo.
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 20 * 1024 * 1024  # 20MB

WAGTAIL_PASSWORD_MANAGEMENT_ENABLED = True

# Used in the admin ("Ferme Sénégalaise") and in notification e-mails.
WAGTAILADMIN_NOTIFICATION_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default="no-reply@lafermesenegalaise.sn"
)

# Multilingual readiness ----------------------------------------------------
# Kept OFF at launch (French-only content, per project decision). Flipping
# WAGTAIL_I18N_ENABLED to True later + running `wagtail bootstrap_translation`
# is the documented upgrade path to add English without restructuring pages.
WAGTAIL_I18N_ENABLED = False
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

# Contact form / site owner notification address.
CONTACT_FORM_RECIPIENT_EMAIL = env(
    "CONTACT_FORM_RECIPIENT_EMAIL", default="contact@lafermesenegalaise.sn"
)

# Default map view (centered on Dakar, Sénégal). Leaflet is loaded from
# cdnjs directly in templates (see locations/contact templates); no
# django-leaflet dependency, which pulls in GeoDjango/GDAL bindings that
# aren't available on every deployment target (and aren't needed since
# Location stores plain lat/lng decimals, not a GEOS PointField).
MAP_DEFAULT_CENTER = (14.6928, -17.4467)
MAP_DEFAULT_ZOOM = 7

# Map tiles for the "Points de vente" page. Free, no-key tile providers
# (OpenStreetMap's own server, CARTO's anonymous basemaps) are meant for
# evaluation, not production: OSM's usage policy blocks sites that send it
# real traffic, and CARTO now serves an "API key required" watermark tile
# instead of the map. MapTiler's free tier (100 000 loads/month, no card
# required, https://cloud.maptiler.com/) is the supported production path.
# Until a key is set, the template falls back to OpenStreetMap's tiles,
# which is fine for local development but not guaranteed to stay working
# once the site is live.
MAPTILER_API_KEY = env("MAPTILER_API_KEY", default="")

# Google Analytics 4 / Search Console, read from env, empty by default so
# nothing tracks visitors until the client supplies real IDs.
GA4_MEASUREMENT_ID = env("GA4_MEASUREMENT_ID", default="")
GOOGLE_SITE_VERIFICATION = env("GOOGLE_SITE_VERIFICATION", default="")
