# Generated by Django 6.1.1 on 2026-09-13 12:11

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text="Numéro affiché dans l'en-tête et le pied de page, ex. +221 33 000 00 00", max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Numéro international sans espaces ni +, ex. 221770000000 (pour le lien WhatsApp).', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, default='Dakar, Sénégal', max_length=100)),
                ('opening_hours', models.CharField(blank=True, help_text='Ex. Lun–Ven : 8h–18h · Sam : 9h–13h', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('footer_about_text', wagtail.fields.RichTextField(blank=True, help_text='Court paragraphe de présentation affiché en pied de page.')),
                ('newsletter_intro', models.CharField(blank=True, default='Recevez nos actualités et nos offres directement par e-mail.', max_length=255)),
                ('copyright_holder', models.CharField(blank=True, default='La Ferme Sénégalaise SAS', max_length=255)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text="URL d'intégration Google Maps (facultatif, sinon la carte utilise OpenStreetMap).")),
                ('legal_notice_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Mentions légales')),
                ('privacy_policy_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Politique de confidentialité')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Réglages du site',
            },
        ),
    ]
