# Generated by Django 6.1.1 on 2026-09-13 12:11

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page « Nos activités »',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ActivityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('icon', models.CharField(choices=[('seedling', 'Production végétale'), ('home', 'Production animale / élevage'), ('water', 'Pisciculture'), ('bolt', 'Transformation agroalimentaire'), ('handshake', 'Commercialisation'), ('shield', 'Prestations de services')], default='seedling', max_length=30)),
                ('summary', models.CharField(help_text='Résumé affiché sur la vignette de la page « Nos activités ».', max_length=280)),
                ('body', wagtail.fields.StreamField([('hero', 11), ('text', 16), ('image_text', 21), ('stats', 26), ('values', 32), ('timeline', 36), ('testimonials', 43), ('logo_cloud', 46), ('gallery_preview', 49), ('documents', 52), ('video', 54), ('cta', 58)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus du titre, ex. « SAS créée en 2026 »', 'label': 'Sur-titre', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'max_length': 140}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Sous-titre', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image de fond', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'max_length': 60}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page interne (prioritaire)', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'ou lien externe', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Plein (primaire)'), ('secondary', 'Contour (secondaire)')], 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('url', 6), ('style', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': "Boutons d'appel à l'action", 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('dark', 'Sombre (texte blanc)'), ('brand', 'Dégradé vert de marque'), ('light', 'Clair (texte foncé)')], 'label': 'Habillage', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('subheading', 2), ('image', 3), ('buttons', 9), ('overlay', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Sur-titre', 'max_length': 80, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'max_length': 140, 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Aligné à gauche'), ('center', 'Centré')], 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('eyebrow', 12), ('heading', 13), ('body', 14), ('alignment', 15)]], {}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('leaf', 'Feuille (durabilité)'), ('sun', 'Soleil (énergie/vitalité)'), ('water', 'Eau (pisciculture)'), ('shield', 'Bouclier (qualité/sécurité)'), ('handshake', 'Poignée de main (proximité/équité)'), ('bolt', 'Éclair (réactivité)'), ('home', 'Maison (ferme/famille)'), ('globe', 'Globe (souveraineté alimentaire)'), ('seedling', 'Pousse (production végétale)')], 'label': "Icône (si aucune image n'est choisie)", 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('url', 6), ('style', 7)]], {'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image à gauche'), ('right', 'Image à droite')], 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('image', 17), ('fallback_icon', 18), ('eyebrow', 12), ('heading', 13), ('body', 14), ('button', 19), ('image_position', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex. 12, 4500, 100%', 'label': 'Chiffre', 'max_length': 20}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé', 'max_length': 100}), 24: ('wagtail.blocks.StructBlock', [[('number', 22), ('label', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Chiffres clés'}), 26: ('wagtail.blocks.StructBlock', [[('heading', 13), ('stats', 25)]], {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('leaf', 'Feuille (durabilité)'), ('sun', 'Soleil (énergie/vitalité)'), ('water', 'Eau (pisciculture)'), ('shield', 'Bouclier (qualité/sécurité)'), ('handshake', 'Poignée de main (proximité/équité)'), ('bolt', 'Éclair (réactivité)'), ('home', 'Maison (ferme/famille)'), ('globe', 'Globe (souveraineté alimentaire)'), ('seedling', 'Pousse (production végétale)')], 'label': 'Icône'}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'max_length': 100}), 29: ('wagtail.blocks.TextBlock', (), {'label': 'Description'}), 30: ('wagtail.blocks.StructBlock', [[('icon', 27), ('title', 28), ('text', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Cartes'}), 32: ('wagtail.blocks.StructBlock', [[('eyebrow', 12), ('heading', 13), ('cards', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'label': 'Année / date', 'max_length': 20}), 34: ('wagtail.blocks.StructBlock', [[('year', 33), ('text', 29)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {'label': 'Étapes'}), 36: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 35)]], {}), 37: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 38: ('wagtail.blocks.CharBlock', (), {'label': 'Nom', 'max_length': 100}), 39: ('wagtail.blocks.CharBlock', (), {'label': 'Fonction / structure', 'max_length': 140, 'required': False}), 40: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo', 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('quote', 37), ('author', 38), ('role', 39), ('photo', 40)]], {}), 42: ('wagtail.blocks.ListBlock', (41,), {'label': 'Témoignages'}), 43: ('wagtail.blocks.StructBlock', [[('heading', 13), ('items', 42)]], {}), 44: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 45: ('wagtail.blocks.ListBlock', (44,), {'label': 'Logos'}), 46: ('wagtail.blocks.StructBlock', [[('heading', 13), ('logos', 45)]], {}), 47: ('wagtail.blocks.ListBlock', (44,), {'label': 'Images'}), 48: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Voir toute la galerie (page)', 'required': False}), 49: ('wagtail.blocks.StructBlock', [[('heading', 13), ('images', 47), ('link_page', 48)]], {}), 50: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 51: ('wagtail.blocks.ListBlock', (50,), {'label': 'Documents'}), 52: ('wagtail.blocks.StructBlock', [[('heading', 13), ('documents', 51)]], {}), 53: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Lien vidéo (YouTube, Vimeo...)'}), 54: ('wagtail.blocks.StructBlock', [[('heading', 13), ('embed', 53)]], {}), 55: ('wagtail.blocks.TextBlock', (), {'label': 'Texte', 'required': False}), 56: ('wagtail.blocks.ListBlock', (8,), {'label': 'Boutons'}), 57: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('brand', 'Fond vert de marque'), ('dark', 'Fond sombre (terre)')], 'required': False}), 58: ('wagtail.blocks.StructBlock', [[('heading', 1), ('text', 55), ('buttons', 56), ('style', 57)]], {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ActivityGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='activities.activitypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
