# Generated by Django 6.1.1 on 2026-09-13 12:11

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page « Points de vente »',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('exploitation', 'Exploitation / ferme'), ('point_de_vente', 'Point de vente'), ('distribution', 'Centre de distribution'), ('siege', 'Siège social')], default='point_de_vente', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Dakar', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.locationspage')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
    ]
